<?php

/**
 * @file
 * Functions to support theming in the client theme.
 */

declare(strict_types=1);

/**
 * Implements hook_theme_suggestions_alter().
 */
function client_theme_suggestions_alter(array &$suggestions, array $variables, string $hook): void {
  if ($hook == 'form' & !empty($variables['element']['#id'])) {
    $suggestions[] = 'form__' . str_replace('-', '_', $variables['element']['#id']);
  }
}
